version: '3.9'

services:
  db:
    image: postgres:16.2-alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432

volumes:
  pgdata:
